apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-routr-connect
  namespace: {{ .Release.Namespace }}
  {{- with .Values.connect.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include ".helm.labels" . | nindent 4 }}
    service: connect
spec:
  ports:
  - port: 51904
    targetPort: 51904
  selector:
    {{- include ".helm.selectorLabels" . | nindent 4 }}
    service: connect
