apiVersion: v2
name: routr-connect
description: Routr Connect Helm Chart
type: application
version: 0.1.6
appVersion: 2.1.3
dependencies:
  - name: postgresql
    version: 12.1.15
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 17.7.3
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
