## Learn more about this file at 'https://www.gitpod.io/docs/references/gitpod-yml'
##
## This '.gitpod.yaml' file when placed at the root of a project instructs
## Gitpod how to prepare & build the project, start development environments
## and configure continuous prebuilds. Prebuilds when enabled builds a project
## like a CI server so you can start coding right away - no more waiting for
## dependencies to download and builds to finish when reviewing pull-requests
## or hacking on something new.
##
tasks:
  - name: Setup & start
    before: sudo sh -c "cat etc/hosts.txt >> /etc/hosts && mkdir -p /etc/routr/certs && cp etc/certs/signaling.p12 /etc/routr/certs/signaling.p12"
    init: npm run make
    command: npm start

ports:
  - name: Dispatcher
    description: Dispatcher service port
    port: 51901
    onOpen: ignore
  - name: Location
    description: Location service port
    port: 51902
    onOpen: ignore
  - name: Processor
    description: Processor service port
    port: 51904
    onOpen: ignore
  - name: SIP UDP/TCP
    description: SIP signaling ports for UDP/TCP
    port: 5060
    onOpen: ignore
  - name: SIP TLS
    description: SIP signaling ports for TLS
    port: 5061
    onOpen: ignore
  - name: SIP WS
    description: SIP signaling ports for Websocket
    port: 5062
    onOpen: ignore
    visibility: public
  - name: SIP WSS
    description: SIP signaling ports for Secure Websocket
    port: 5063
    onOpen: ignore
  - name: Exra SIP UDP/TCP
    description: Extra SIP signaling ports for UDP/TCP
    port: 6060
    onOpen: ignore
  - name: Exra SIP TLS
    description: Extra SIP signaling ports for TLS
    port: 6061
    onOpen: ignore
  - name: Extra SIP WS
    description: Extra SIP signaling ports for Websocket
    port: 6062
    onOpen: ignore
    visibility: public
  - name: Extra SIP WSS
    description: Extra SIP signaling ports for Secure Websocket
    port: 6063
    onOpen: ignore