services:

  # RTPEngine requires of network mode "host" to work properly. However, this option doesn't work on OSX.
  # For development, we are opening a few ports to the host machine. For production, you must use 
  # the network_mode: host which works on Linux.
  rtpengine:
    image: fonoster/rtpengine:latest
    restart: always
    # Uncomment the following line for production
    # network_mode: host
    environment:
      # Set DOCKER_HOST_ADDRESS to an IP address that is reachable to the SIP clients
      PUBLIC_IP: ${DOCKER_HOST_ADDRESS}
      PORT_MIN: 10000
      PORT_MAX: 10020
      LOG_LEVEL: 8
    ports:
      - 22222:22222/udp
      - 10000-10020:10000-10020/udp

  redis:
    image: redis:7.0.8-alpine
    restart: always
    ports:
      - 6379:6379

  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: UTC
      PGTZ: UTC
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    ports:
      - 8080:8080

volumes:
  db:
    driver: local
