apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-routr-registry
  labels:
    {{- include ".helm.labels" . | nindent 4 }}
    service: registry
spec:
  selector:
    matchLabels:
      {{- include ".helm.selectorLabels" . | nindent 6 }}
      service: registry
  template:
    metadata:
      annotations:
      {{- with .Values.registry.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
        checksum/config: {{ include (print $.Template.BasePath "/registry/configmaps.yaml") . | sha256sum }}    
      labels:
        {{- include ".helm.selectorLabels" . | nindent 8 }}
        service: registry
    spec:
      securityContext:
        runAsUser: {{ .Values.registry.securityContext.runAsUser }}
        runAsGroup: {{ .Values.registry.securityContext.runAsGroup }}
        fsGroup: {{ .Values.registry.securityContext.fsGroup }}
      containers:
        - name: registry
          image: "{{ .Values.registry.image.repository }}:{{ .Values.registry.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.registry.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: {{ .Values.registry.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.registry.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.registry.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.registry.livenessProbe.failureThreshold }}
            timeoutSeconds: {{ .Values.registry.livenessProbe.timeoutSeconds }}          
          env:
            - name: LOGS_LEVEL
              value: {{ .Values.global.logsLevel }}
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              value: {{ .Values.global.otlExporter }}
          ports:
            - containerPort: 8080
            - containerPort: 51901
          volumeMounts:
            - name: config
              mountPath: /etc/routr/registry.yaml
              subPath: registry.yaml
          resources:
            {{- if .Values.registry.resources.limits }}
            limits:
            {{- .Values.registry.resources.limits | toYaml | nindent 14 }}
            {{- end }}
            {{- if .Values.registry.resources.requests }}
            requests:
            {{- .Values.registry.resources.requests | toYaml | nindent 14 }}
            {{- end }}
          securityContext:
            allowPrivilegeEscalation: {{ .Values.registry.securityContext.allowPrivilegeEscalation }}           
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-routr-registry-config
