Configuration:
  Appenders:
    Console:
      PatternLayout:
        pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%-4level{lowerCase=true}]: (${sys:serviceName}) %c{1}.java %msg%n"
      name: Console
      target: SYSTEM_OUT
    RollingFile:
      - name: LogToRollingFile
        fileName: logs/routr.log
        filePattern: "logs/routr-%d{MM-dd-yyyy}-%i.log.gz"
        PatternLayout:
          pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%-4level{lowerCase=true}]: (${sys:serviceName}) %c{1}.java %msg%n"
        Policies:
          SizeBasedTriggeringPolicy:
            size: 10MB
        DefaultRollOverStrategy:
          max: 10
  Loggers:
    Logger:
      - name: io.routr
        level: info
        AppenderRef:
          - ref: Console
          - ref: LogToRollingFile
    Root:
      level: error
      AppenderRef:
        - ref: LogToRollingFile
