- apiVersion: v2beta1
  kind: Peer
  ref: peer-01
  metadata:
    name: Asterisk (Media Server)
  spec:
    aor: sip:conference@sip.local
    username: asterisk
    credentialsRef: credentials-03
    loadBalancing:
     withSessionAffinity: true
     algorithm: least-sessions

- apiVersion: v2beta1
  kind: Peer
  ref: peer-02
  metadata:
    name: FS Voice Feature Server
  spec:
    aor: sip:voice@sip.local
    username: freeswitch
    credentialsRef: credentials-05
    loadBalancing:
      algorithm: round-robin
