apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-routr-location
  namespace: {{ .Release.Namespace }}  
  labels:
    {{- include ".helm.labels" . | nindent 4 }}
    service: location
spec:
  selector:
    matchLabels:
      {{- include ".helm.selectorLabels" . | nindent 6 }}
      service: location
  template:
    metadata:
      annotations:
      {{- with .Values.location.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
        checksum/config: {{ include (print $.Template.BasePath "/location/configmaps.yaml") . | sha256sum }}      
      labels:
        {{- include ".helm.selectorLabels" . | nindent 8 }}
        service: location
    spec:
      securityContext:
        runAsUser: {{ .Values.location.securityContext.runAsUser }}
        runAsGroup: {{ .Values.location.securityContext.runAsGroup }}
        fsGroup: {{ .Values.location.securityContext.fsGroup }}
      containers:
        - name: location
          image: "{{ .Values.location.image.repository }}:{{ .Values.dispatcher.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.location.image.pullPolicy }}
          livenessProbe:
            grpc:
              port: 51902
            initialDelaySeconds: {{ .Values.location.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.location.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.location.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.location.livenessProbe.failureThreshold }}
            timeoutSeconds: {{ .Values.location.livenessProbe.timeoutSeconds }}
          env:
            - name: LOGS_LEVEL
              value: {{ .Values.global.logsLevel }}
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              value: {{ .Values.global.otlExporter }}
          ports:
            - containerPort: 51902
          volumeMounts:
            - name: config
              mountPath: /etc/routr/location.yaml
              subPath: location.yaml
          resources:
            {{- if .Values.dispatcher.resources.limits }}
            limits:
            {{- .Values.dispatcher.resources.limits | toYaml | nindent 14 }}
            {{- end }}
            {{- if .Values.dispatcher.resources.requests }}
            requests:
            {{- .Values.dispatcher.resources.requests | toYaml | nindent 14 }}
            {{- end }}
          securityContext:
            allowPrivilegeEscalation: {{ .Values.location.securityContext.allowPrivilegeEscalation }}          
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-routr-location-config
