name: publish charts to github pages (v2)

on:
  workflow_dispatch:
  push:
    paths:
      - 'ops/**'
    branches:
      - main

jobs:
  deployment:
    name: Build & Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout routr repo
        uses: actions/checkout@v3
        with:
          path: routr
          ref: gh-pages
      - name: Save charts directory
        run: |
          mkdir -p /tmp/charts
          cp -a routr/charts/* /tmp/charts
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: latest
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Package charts
        run: |
          mv /tmp/charts charts
          helm package ops/charts/connect -d charts
          helm repo index charts --merge charts/index.yaml
      - name: Build sources
        run: mkdir -p public && mv charts public/charts
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          keep_files: true
